[theme]

# Primary accent for interactive elements
primaryColor = 'E4BD78'

# Background color for the main content area
backgroundColor = '#b7a793'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = 'F3E5AB'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"